/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yan.Ren' at '2/6/17 2:36 PM' with Gradle 2.14.1
 *
 * @author Yan.Ren, @date 2/6/17 2:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
